config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/users/:id', to: 'users#show', as: :user
  root to: 'posts#index'
  resources :posts do
    member do
      put 'upvote', to: 'posts#upvote'
      put 'downvote', to: 'posts#downvote'
    end
    resources :comments, only: [:create, :destroy, :edit, :update]
  end

end

app/models/comment.rb
# Comment: a comment made by a user, attached to a post
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates_presence_of :body
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :authenticate_user!
  before_action :authorize_ownership!, only: [:edit, :update, :destroy]

  def edit
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @post, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { head status: :unprocessable_entity }
      end
    end
  end

  def create
    @comment = current_user.comments.new(comment_params)
    @comment.post = @post

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { redirect_to @post, alert: 'Comments must not be blank.' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy!
    respond_to do |format|
      format.html { redirect_to @post, notice: 'Comment was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  rescue
    redirect_to :root
  end

  def comment_params
    params.require(:comment).permit(:body)
  end

  def authorize_ownership!
    @comment = current_user.comments.find_by(params.permit(:id, :post_id))
    return unless @comment.nil?
    redirect_to @post
    flash[:alert] = 'You are not authorized to perform that operation'
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_list.html.erb
<ul class="list-group">
  <% comments.each do |comment| %>
    <li class="list-group-item comment">
      <div class="comment-body">
        <%= markdown(comment.body) %>
      </div>
      <div class='small' class="comment-meta">
        Posted <%= time_ago_in_words(comment.created_at) %> ago
        <% if controller.controller_name != 'users' %>
          by <%= link_to comment.user.username, comment.user %>
        <% end %>
        <% if controller.controller_name != 'posts' %>
          in <%= link_to comment.post.title, comment.post %>
        <% end %>
        <% if user_signed_in? && comment.user == current_user %>
          <div class="btn-group comment-actions">
            <%= link_to 'Edit', edit_post_comment_path(comment.post, comment),
                  class: 'btn btn-xs btn-default' %>
            <%= link_to 'Delete', post_comment_path(id: comment.id, post_id: comment.post_id),
                  class: 'btn btn-xs btn-danger',
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %>
          </div>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>

app/views/comments/_new.html.erb
<div class="panel panel-default devise-bs">
  <div class="panel-heading">
    <div class="panel-title">Leave a Comment</div>
  </div>
  <div class="panel-body">
    <%= form_for([@post, @comment]) do |f| %>
      <div class="form-group">
        <%= f.label :body, class: 'sr-only' %>
        <%= f.text_area :body, rows: 5, autofocus: true, class: "form-control" %>
      </div>
      <%= f.submit  t('.sign_in', :default => "Leave comment"), class: "btn btn-primary form-control" %>
    <% end %>
  </div>
</div>

app/views/comments/edit.html.erb
<div class="panel panel-default devise-bs">
  <div class="panel-heading">
    <div class="panel-title">Edit a Comment</div>
  </div>
  <div class="panel-body">
    <%= form_for([@post, @comment]) do |f| %>
      <div class="form-group">
        <%= f.label :body, class: 'sr-only' %>
        <%= f.text_area :body, rows: 5, autofocus: true, class: "form-control" %>
      </div>
      <%= f.submit  t('.sign_in', :default => "Leave comment"), class: "btn btn-primary form-control" %>
    <% end %>
  </div>
</div>