config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/users/:id', to: 'users#show', as: :user
  root to: 'posts#index'
  resources :posts do
    member do
      put 'upvote', to: 'posts#upvote'
      put 'downvote', to: 'posts#downvote'
    end
    resources :comments, only: [:create, :destroy, :edit, :update]
  end

end

app/models/post.rb
# Post: A posted URL with a title, description, and comments
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  validates :title, presence: true
  validates :title, length: { minimum: 3, maximum: 140 }

  validates :url, uri: true
  validates :url, presence: true, if: :link
  validates :url, length: { minimum: 3, maximum: 140 }, if: :link

  validates :description, presence: true, unless: :link
  validates :description, length: { minimum: 20, maximum: 2000 }, unless: :link

  acts_as_votable

  def host
    URI.parse(full_url).host
  rescue URI::InvalidURIError
    nil
  end

  def full_url
    uri = URI.parse(self[:url])
    uri.scheme ? self[:url] : 'http://' + self[:url]
  rescue URI::InvalidURIError
    self[:url]
  end

  def score
    cached_votes_score
  end

  def link?
    url.present?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authorize_ownership!, only: [:edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order(cached_votes_score: :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    return unless user_signed_in?
    @comment = current_user.comments.new
    @comment.post = @post
  end

  # GET /posts/new
  def new
    @post = current_user.posts.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)
    @post.link = false if @post.url.blank?

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @post.upvote_by current_user if user_signed_in?
    redirect_to :back
  end

  def downvote
    @post.downvote_by current_user if user_signed_in?
    redirect_to :back
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :url, :description, :link)
  end

  def authorize_ownership!
    @post = current_user.posts.find_by_id(params.fetch(:id))
    return unless @post.nil?
    redirect_to root_path
    flash[:alert] = 'You are not authorized to perform that operation'
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_errors.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-danger" id="error_explanation">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <strong><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</strong>

    <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :url %><br>
    <%= f.text_field :url, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, rows: 10, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-primary form-control' %>
  </div>
<% end %>

app/views/posts/_list.html.erb
<ul class="list-group">
  <% posts.each do |post| %>
    <li class="post list-group-item">
      <%= render 'posts/votes', post: post %>
      <h4 class="title">
        <%= link_to post.title, post %>
        <% if post.link %>
          <span class="small glyphicon glyphicon-link"></span>
          <small>(<%= post.host %>)</small>
        <% end %>
      </h4>
      <small class="author">
        Submitted <%= time_ago_in_words(post.created_at) %>
        by <%= link_to post.user.username, post.user %>
      </small>
      <div class="badge badge-comments"><%= pluralize post.comments.count, 'comment' %></div>
    </li>
  <% end %>
</ul>

app/views/posts/_votes.html.erb
<div class="votes btn-group-vertical">
  <% if user_signed_in? and current_user.voted_up_on? post %>
    <div class="upvote btn btn-xs btn-success"><i class="fa fa-chevron-up upvoted"></i></div>
  <% elsif user_signed_in? %>
    <%= link_to upvote_post_path(post), class: 'upvote btn btn-xs btn-default', method: :put do %>
      <i class="fa fa-chevron-up"></i>
    <% end %>
  <% else %>
    <div class="upvote btn btn-xs btn-default"><i class="fa fa-chevron-up"></i></div>
  <% end %>

  <% if user_signed_in? and current_user.voted_on? post %>
    <div class="votes_score voted btn btn-xs btn-default"><%= post.score %></div>
  <% else %>
    <div class="votes_score btn btn-xs btn-default"><%= post.score %></div>
  <% end %>

  <% if user_signed_in? and current_user.voted_down_on? post %>
    <div class="downvote btn btn-xs btn-danger"><i class="fa fa-chevron-down downvoted"></i></div>
  <% elsif user_signed_in? %>
    <%= link_to downvote_post_path(post), class: 'downvote btn btn-xs btn-default', method: :put do %>
      <i class="fa fa-chevron-down"></i>
    <% end %>
  <% else %>
    <div class="downvote btn btn-xs btn-default"><i class="fa fa-chevron-down"></i></div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= render 'errors' %>

<h1>Editing Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<ul class="list-group">
  <% @posts.each do |post| %>
    <li class="post list-group-item">
      <%= render 'votes', post: post %>
      <h4 class="title">
        <%= link_to post.title, post %>
        <% if post.link %>
          <span class="small glyphicon glyphicon-link"></span>
          <small>(<%= post.host %>)</small>
        <% end %>
      </h4>
      <small class="author">
        Submitted <%= time_ago_in_words(post.created_at) %>
        by <%= post.user.username %>
      </small>
      <div class="badge badge-comments"><%= pluralize post.comments.count, 'comment' %></div>
    </li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<%= render 'errors' %>

<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="panel panel-default post">
  <div class="panel-heading">
    <%= render 'votes', post: @post %>
    <h4>
      <% if @post.link %>
        <%= link_to @post.title, @post.full_url %>
        <span class="small glyphicon glyphicon-link"></span>
        <small>(<%= @post.host %>)</small>
      <% else %>
        <%= @post.title %>
      <% end %>
    </h4>
    <small>
      Submitted <%= time_ago_in_words(@post.created_at) %>
      by <%= link_to @post.user.username, @post.user %>
    </small>
  </div>
  <div class="panel-body post-description">
    <% if @post.description.present? %>
      <%= markdown(@post.description) %>
    <% else %>
      No description
    <% end %>
  </div>
  <% if user_signed_in? && current_user == @post.user %>
    <div class="panel-footer clearfix">
      <div class="btn-group pull-right">
        <%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-xs btn-default' %>
        <%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %>
      </div>
    </div>
  <% end %>
</div>

<%= render 'comments/new' if user_signed_in? %>
<div class="panel panel-default comments">
  <div class="panel-heading">
    <div class="panel-title">
      Comments
      <span class="small"><%= @post.comments.count %> total</span>
    </div>
  </div>
  <%= render 'comments/list', comments: @post.comments.reverse %>
</div>